# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/pix_auditoria
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Envers
spring.jpa.properties.org.hibernate.envers.audit_table_suffix=_aud
spring.jpa.properties.org.hibernate.envers.store_data_at_delete=true

# Security (para popular SecurityContext em dev/teste)
spring.security.user.name=admin
spring.security.user.password=admin